# .goreleaser.yml
# Build customization
builds:
  - binary: hcledit
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/minamijoyo/hcledit/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
release:
  prerelease: auto
changelog:
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - Update README
      - Update CHANGELOG
brews:
  - github:
      owner: minamijoyo
      name: homebrew-hcledit
    commit_author:
      name: "Masayuki Morita"
      email: minamijoyo@gmail.com
    homepage: https://github.com/minamijoyo/hcledit
    description: "A command line editor for HCL"
    skip_upload: auto
    test: |
      system "#{bin}/hcledit version"
    install: |
      bin.install "hcledit"
